### ISSUE TITLE
Связать с моделью

### ISSUE THREAD

**Issue by loveorigami** [himiklab/yii2-handsontable-widget#3]
Спасибо за виджет. Полезная штука для редактирования прайсов.
Получить вид с данными вроде не проблема, а вот как данные записать в базу при редактировании ячейки?

Например:
по строкам - даты, 
по колонкам - id товара
в ячейке - цена товара в зависимости от даты.

**Comment by himiklab** [comment]
Хорошая, но https://github.com/himiklab/yii2-sitemap-module лучше. ;) В этом гриде я реализовал редактирование и кучу чего ещё. А handsontable пока заниматься некогда, хотя он неслабо так развился и там есть на что посмотреть.
