### ISSUE TITLE
Pikaday assets 

### ISSUE THREAD

**Issue by stronglab** [himiklab/yii2-handsontable-widget#4]
Календарь не работает, необходимо вручную подключать ассеты из бовера.
=====================================================
use yii\web\AssetBundle;

class customHandsontableAssets extends AssetBundle
{
    public $sourcePath = '@bower/';

    public function init()
    {
        parent::init();
        $this->js[] = YII_DEBUG ? 'moment/moment.js' : 'moment/min/moment.min.js';
        $this->js[] = 'pikaday/pikaday.js';
        $this->css[] = 'pikaday/css/pikaday.css';
    }
}

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-handsontable-widget/commit/d6cb075ad8bf75f3068952985a2da82f6b810fa3
