### ISSUE TITLE
Update handsontable plugin

### ISSUE THREAD

**Issue by servocoder** [himiklab/yii2-handsontable-widget#5]
Hey,
Handsontable 0.20.2 is released.
I suggest you to change the line in composer.json
```
"bower-asset/handsontable": "~0.18.0"
```
to
```
"bower-asset/handsontable": "*"
```

To not update your package for every plugin release.
Thank you.

**Comment by pfmcastro** [comment]
one more vote :) 0.20.3 now

**Comment by himiklab** [comment]
OK :)
https://github.com/himiklab/yii2-handsontable-widget/commit/c220ca2c13a21d68971fe62d23d71f1804630c97
